# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d443b567103b7dc056fc2f926c7c14c1643c063d4164305629152e02ba3e86dae716d40b74969d7889e8b9b9d27de4e25981f782aa6d015c185833669c39b128

test:
  secret_key_base: f6e2f8c8c7326b93fb0e81577e44b5782ce45c4b03f5c4d8b4062d8f386917fda0b10859c91cadba04dff6d27821d271f9e4779973dc2565bc4db2853ef52760

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
